obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.6,0.4], [0.6,0.4], [0.6,-0.4], [-0.6,-0.4]]
#robot_radius: ir_of_robot
inflation_radius: 0.4

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: realsense, data_type: PointCloud2, topic: /camera/depth/color/points, marking: true, clearing: true}
